INSERT INTO MLBINFO VALUES (0,'Arizona Diamondbacks','Chase Field',48686,'Phoenix, Arizona','Grass','National',1998,407,'Retro Modern','Retractable');
INSERT INTO MLBINFO VALUES (1,'Atlanta Braves','SunTrust Park',41149,'Cumberland, Georgia','Grass','National',2017,400,'Retro Modern','Open');
INSERT INTO MLBINFO VALUES (2,'Baltimore Orioles','Oriole Park at Camden Yards',45971,'Baltimore, Maryland','Grass','American',1992,410,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (3,'Boston Red Sox','Fenway Park',37731,'Boston, Massachusetts','Grass','American',1912,420,'Jewel Box','Open');
INSERT INTO MLBINFO VALUES (4,'Chicago Cubs','Wrigley Field',41268,'Chicago, Illinois','Grass','National',1914,400,'Jewel Box','Open');
INSERT INTO MLBINFO VALUES (5,'Chicago White Sox','Guaranteed Rate Field',40615,'Chicago, Illinois','Grass','American',1991,400,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (6,'Cincinnati Reds','Great American Ball Park',42319,'Cincinnati, Ohio','Grass','National',2003,404,'Retro Modern','Open');
INSERT INTO MLBINFO VALUES (7,'Cleveland Indians','Progressive Field',35051,'Cleveland, Ohio','Grass','American',1994,410,'Retro Modern','Open');
INSERT INTO MLBINFO VALUES (8,'Colorado Rockies','Coors Field',50398,'Denver, Colorado','Grass','National',1995,415,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (9,'Detroit Tigers','Comerica Park',41299,'Detroit, Michigan','Grass','American',2000,420,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (10,'Houston Astros','Minute Maid Park',41168,'Houston, Texas','Grass','American',2000,409,'Retro Modern','Retractable');
INSERT INTO MLBINFO VALUES (11,'Kansas City Royals','Kauffman Stadium',37903,'Kansas City, Missouri','Grass','American',1973,410,'Retro Modern','Open');
INSERT INTO MLBINFO VALUES (12,'Los Angeles Angels','Angel Stadium',45477,'Anaheim, California','Grass','American',1966,396,'Retro Modern','Open');
INSERT INTO MLBINFO VALUES (13,'Los Angeles Dodgers','Dodger Stadium',56000,'Los Angeles, California','Grass','National',1962,400,'Modern','Open');
INSERT INTO MLBINFO VALUES (14,'Miami Marlins','Marlins Park',36742,'Miami, Florida','Grass','National',2012,407,'Contemporary','Retractable');
INSERT INTO MLBINFO VALUES (15,'Milwaukee Brewers','Miller Park',41900,'Milwaukee, Wisconsin','Grass','National',2001,400,'Retro Modern','Retractable');
INSERT INTO MLBINFO VALUES (16,'Minnesota Twins','Target Field',38885,'Minneapolis, Minnesota','Grass','American',2010,404,'Retro Modern','Open');
INSERT INTO MLBINFO VALUES (17,'New York Mets','Citi Field',41922,'Queens, New York','Grass','National',2009,408,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (18,'New York Yankees','Yankee Stadium',47422,'Bronx, New York','Grass','American',2009,408,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (19,'Oakland Athletics','Oakland–Alameda County Coliseum',47170,'Oakland, California','Grass','American',1966,400,'Multipurpose','Open');
INSERT INTO MLBINFO VALUES (20,'Philadelphia Phillies','Citizens Bank Park',43651,'Philadelphia, Pennsylvania','Grass','National',2004,401,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (21,'Pittsburgh Pirates','PNC Park',38362,'Pittsburgh, Pennsylvania','Grass','National',2001,399,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (22,'San Diego Padres','Petco Park',40209,'San Diego, California','Grass','National',2004,396,'Retro Modern','Open');
INSERT INTO MLBINFO VALUES (23,'San Francisco Giants','Oracle Park',41915,'San Francisco, California','Grass','National',2000,399,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (24,'Seattle Mariners','Safeco Field',47943,'Seattle, Washington','Grass','American',1999,401,'Retro Modern','Retractable');
INSERT INTO MLBINFO VALUES (25,'St. Louis Cardinals','Busch Stadium',45529,'St. Louis, Missouri','Grass','National',2006,400,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (26,'Tampa Bay Rays','Tropicana Field',31042,'St. Petersburg, Florida','AstroTurf GameDay Grass','American',1990,404,'Multipurpose','Fixed');
INSERT INTO MLBINFO VALUES (27,'Texas Rangers','Globe Life Park in Arlington',48114,'Arlington, Texas','Grass','American',1994,400,'Retro Classic','Open');
INSERT INTO MLBINFO VALUES (28,'Toronto Blue Jays','Rogers Centre',49282,'Toronto, Ontario','AstroTurf GameDay Grass 3D','American',1989,400,'Multipurpose','Retractable');
INSERT INTO MLBINFO VALUES (29,'Washington Nationals','Nationals Park',41339,'Washington, D.C.','Grass','National',2008,402,'Retro Modern','Open');
